spring:

  application:
    name: restful-api-jwt

  datasource:
    url: jdbc:postgresql://localhost:5432/restful-api-jwt
    driver-class-name: org.postgresql.Driver
    username: ${PSQL_USER}
    password: ${PSQL_PASS}
    hikari:
      schema: public

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # My ISP is blocking port 587, so I have to use port 465
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: ${MAIL_USER}
  #    password: ${MAIL_PASS}
  #    protocol: smtp
  #    properties:
  #      mail:
  #        debug: true
  #        transport:
  #          protocol: smtp
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true
  #            required: true

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: smtp.gmail.com
            checkserveridentity: true
        debug: false

server:
  port: 8080
  error:
    include-message: never
    include-exception: off
    include-stacktrace: never



jwt:
  secret:
    key: ${JWT_SECRET_KEY}



